module.exports = {
	HEADER_HOME_BUTTON: 'a > .btn',
	HEADER_LOGO: 'header > a',
	ONPAGE_TITLE: 'h1',
	FILE_HTML: '/file.html',
	HEADER: 'header',
	DROPDOWN_TITLE: '.cen-right-align > fieldset > legend',
	DROPDOWN_OPTIONS: '#dropdown-class-example > option',
	DROPDOWN_CONTAINER: '#dropdown-class-example',
	DROPDOWN_OPTION_TO_SELECT: 'Option2',
	IMAGE_BLOCK_TITLE: 'h3',
	PAGE_WRAPPER: '.wrapper',
	IMAGES: 'img',
	UPLOAD_IMAGE_INPUT: '.image-upload-wrapper > input',
	OPEN_NEW_TAB_TITLE: '.switch-tab',
	OPEN_TAB_BUTTON: '#opentab',
	ALERT_BLOCK_TITLE: '.pull-right > legend',
	ALERT_INPUT: '#name',
	ALERT_BUTTON: '#alertbtn',
	CONFIRM_BUTTON: '#confirmbtn',
	HIDE_SHOW_TITLE: '.block:nth-child(5) > div > fieldset > legend',
	HIDE_SHOW_BLOCK: '.block:nth-child(5) > div > fieldset',
	HIDE_BUTTON: '#hide-textbox',
	HIDE_SHOW_INPUT: '#displayed-text',
	SHOW_BUTTON: '#show-textbox',
	HOVER_BLOCK_TITLE: '.left-align > fieldset > legend',
	HOVER_CONTENT: '.hover-content',
	HOVER_CONTAINER: '.hover-container > .btn',
	HOVER_OPTION_TOP: '[href="#top"]',
	HOVERED: 'hovered',
	IFRAME_TITLE: ':nth-child(7) > fieldset > legend',
	IFRAME: '#courses-iframe',
	IFRAME_WELCOME_PART: 'span:nth-of-type(1) > .animated-line__content',
	IFRAME_WELCOME_PART2: '.animated-line__content2',
	IFRAME_MENU: '.nav__btn',
	IFRAME_MENU_MODAL: '#menu-header-menu',
	IFRAME_MENU_OPTIONS: '.nav__item > a',
	FOOTER: '#gf-BIG',
	FOOTER_SOCIALS_HEADER: 'h4',
	SOCIALS_LINKS: 'td > ul > li > a',
}
