module.exports = {
	TITLE: 'Practice Page',
	HEADER_BTN_HOME_TEXT: 'Home',
	NEW_TITLE: 'Gotoinc test',
	DROPDOWN_TEXT: 'Dropdown',
	IMAGE_BLOCK_TITLE: 'Upload your image here',
	OPEN_TAB_BLOCK_TITLE: 'Open new tab',
	ALERT_INVOKATION_TITLE: 'Invoke an alert/confirmation modal',
	SHOW_HIDE_INPUT_TITLE: 'Show/hide the input',
	HOVER_BLOCK_TITLE_TEXT: 'Hover',
	IFRAME_BLOCK_TITLE: 'iFrame',
	IFRAME_MENU_OPTIONS_ARR_TEXT: [
		'About us',
		'Team',
		'Careers',
		'Case studies',
		'Blog',
		'Get in touch',
	],
	IFRAME_WELCOME_TEXT_PART: 'Your go-to',
	IFRAME_WELCOME_TEXT_PART2: 'tech agency',
	FOOTER_SOCIALS_HEADER_TEXT: 'Social Media',
	FOOTER_SOCIAL_MEDIA_FACEBOOK: 'Facebook',
}
